### ISSUE TITLE
Missing package dependency for `dl_utils`

### ISSUE THREAD

**Issue by kishaloyhalder** [Lou1sM/modular_multimodal_summarization#1]
Hi there,

Upon trying the `compute_metrics.py` example I get the following error:
```
Traceback (most recent call last):
  File "modular_multimodal_summarization/prefs/factscorer.py", line 1, in <module>
    from dl_utils.misc import check_dir
ModuleNotFoundError: No module named 'dl_utils'
python-BaseException
```

Could you please fix this? There are quite a few references of this `dl_utils` module. Thanks!

**Comment by Lou1sM** [comment]
Hi, thanks for pointing this out. `pip install dl-utils385` is what you need. I've just added this to the `environment.yml`, which I see was not up to date, and I'll also add a file listing the packages that need to be installed manually. Feel free to let me know of any other problems.

**Comment by kishaloyhalder** [comment]
Thanks @Lou1sM !
