### ISSUE TITLE
bug in checking malformed sentences sentences

### ISSUE THREAD

**Issue by DJWCB-AUV** [Lou1sM/modular_multimodal_summarization#2]
I noticed in the [compute_metric.py](https://github.com/Lou1sM/modular_multimodal_summarization/blob/main/compute_metrics.py#L135) there is a function checking whether a sentence is malformed. The conditions make sense for checking malformed cases, but when any condition meets the function returns False. Should this be True here? For instance look at this `any(ord(c)>=128 for c in list(sent))`, it clearly checks for any none ascii chars which should be a signal for malformed, but instead it returns false

**Comment by Lou1sM** [comment]
Hi, yes you're right this is a mistake. I used to use `is_wellformed`, then changed to `is_malformed` when uploading the code but forgot to update the Booleans. I pushed a fix there. Thanks for spotting it.
